name: Replace-Tokens

on:
  push:
    branches: [ main, dev ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node-version: [ 14.x, 16.x, 17.x, 18.x ]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build & Test
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test