name: Code Coverage

on:
  push:
    branches: [ main, dev ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/release.yml'
      - '.github/workflows/test-replace-tokens-action-main.yml'
      - '.github/workflows/test-replace-tokens-action-released-tag.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 24.x ]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Set Up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Run Coverage Tests
      run: |
          npm ci
          npm run build --if-present
          npm run coverage

    - name: Upload Coverage Reports To Codecov
      uses: codecov/codecov-action@v6
      with:
        files: ./coverage/lcov.info
        token: ${{ secrets.CODECOV_TOKEN }}
