name: Code Coverage

on:
  push:
    branches: [ main, dev ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 16.x ]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Run Coverage Tests
    - run: npm ci
    - run: npm run coverage

    - name: Upload Coverage To Codecov
      uses: codecov/codecov-action@v3
        env: CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}