name: Release

env:
    RELEASE_NAME: "v1.0"
    RELEASE_NOTES: |
      - Github replace tokens action. (Initial Release)
    DRAFT: false
    PRERELEASE: false
    
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 16.x ]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install (Clean), Build & Test
    - run: |
          npm ci
          npm run build --if-present
          npm test

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.RELEASE_NAME }}
        body: ${{ env.RELEASE_NOTES }}
        draft: ${{ env.DRAFT }}
        prerelease: ${{ env.PRERELEASE }}
        token: ${{ secrets.PAT_REPLACE_TOKENS }}   