name: Test Action (Replace Tokens)

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 16.x ]

    steps:
    - name: Replace Tokens
      uses: abhinavminhas/replace-tokens@main
      with:
        files: package.json
        replacements: true=false
    
    - name: Build & Test
      run: |
          npm ci
          npm run build --if-present
          npm test
