name: Test Action (Replace Tokens)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 16.x ]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Replace Tokens
      uses: abhinavminhas/replace-tokens@main
      with:
        files: package.json
        replacements: true=false
    
    - name: Install (Clean), Build & Test
      run: |
          npm ci
          npm run build --if-present
          npm test